export const EVENT_TYPES = {
    CLIENT_ACTION: 'CLIENT_ACTION',
    CLIENT_RECONNECT: 'CLIENT_RECONNECT',
    SERVER_STATE_SYNC: 'SERVER_STATE_SYNC',
    SERVER_NOTIFICATION: 'SERVER_NOTIFICATION',
    SERVER_ERROR: 'SERVER_ERROR'
};
